In [3]:
import pandas as pd
import numpy as np 
from sklearn import preprocessing 

In [4]:
my_csv = pd.read_csv('C:/Users/NITHIN/Desktop/startups3.csv')

categoriesmap = {}
Investorsmap = {}
investors= my_csv['Investors'].values
investors = investors.tolist()

categories= my_csv['Categories'].values
categories = categories.tolist()

companies = my_csv['Name'].values
companieslist = companies.tolist()
#print(len(companieslist))

In [5]:
m=0
for x in categories:
    categoriesmap.update( {m : categories[m]} )
    m+=1
#print(categoriesmap)

In [6]:
n=0
for inv in investors:
    str = investors[n]
    if pd.isnull(str):
        pass
    else:
        str = str.split(']')
        for x in str:
            singleInvestor = x[x.find("[")+1:x.find("|")]
            if singleInvestor in Investorsmap.keys():
                previouscategories = Investorsmap[singleInvestor]
                newcategories = categoriesmap[n]
                if (pd.isnull(newcategories) | pd.isnull(previouscategories)):
                    categoriesunion = previouscategories
                else:
                    categoriesunion = previouscategories + ","+ newcategories
                Investorsmap.update( {singleInvestor : categoriesunion})
            else:
                Investorsmap.update( {singleInvestor : categories[n]})
    n+=1
#print(Investorsmap)

In [7]:
investorslist = []
categorieslist = []

for key,value in Investorsmap.items():
    investorslist.append(key)
    categorieslist.append(value)
#print(categorieslist)
    
for a in investorslist:
    if a =="":
        investorslist.remove(a)

print(len(investorslist))

for b in companieslist:
    if b=="":
        companieslist.remove(b)
#print(len(companieslist))

592


In [8]:
set_cat = set()
for _,i in enumerate(categorieslist):
    if type(i) == float:
        categorieslist[_] = ""
#print(len(categorieslist))

In [9]:
companycatmap = {}
companycatlist = []

k=0
for map in categories:
    companycatmap.update({k : categories[k]})
    k+=1
#print(len(companycatmap))

for key,value in companycatmap.items():
    companycatlist.append(value)
    
print(len(companycatlist))
print(len(companieslist))

158
158


In [10]:
for ccl in companycatlist:
    if ccl == "":
        companycatlist.remove(ccl)
print(len(companycatlist))

158


In [11]:
set_cat = set()
for i in categorieslist:
    for j in i.split(','):
        set_cat.add(j)
        
set_cat.remove("")
print(len(set_cat))

140


In [12]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
        
lst = []
for i in categorieslist:
    set_temp = set()
    for j in i.split(','):
        if j == "":
            continue
        set_temp.add(j)
    lst.append(set_temp)
    
print(len(lst))

593


In [13]:
investorcategory = mlb.fit_transform(lst)
investorcategory[0]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
from numpy import matrix

b = np.array(investorcategory)
Transinvestorcategory = b.T
Transinvestorcategory[0]

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [20]:
companycatlist = mlb.fit_transform(lst)
companycatlist[0]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
companyinvestor = companycatlist.dot(Transinvestorcategory)
companyinvestor[0]

array([10,  3,  3,  3,  4, 10, 10,  2,  3,  2,  2,  2,  0,  0,  0,  0,  0,
        9,  9,  1,  2,  1,  2,  0,  0,  0,  0,  0,  1,  1,  3,  1,  1,  1,
        1,  1,  1,  4,  0,  0,  0,  0,  1,  1,  9,  1,  2,  2,  8,  3,  9,
        1,  1,  3,  1,  1,  1,  1,  1,  8,  1,  0,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  3,  2,  0,  0,  0,  0,  0,  2,  0,  0,  0,
        0,  0,  0,  1,  1,  1,  8,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  3,  1,  0,  0,  1,  1,  4,  2,  1,  1,  2,  1,  1,  1,  1,  2,
        1,  9,  0,  2,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  2,  1,  0,  2,  0,  0,  0,  1,  1,  0,  0,  1,  0,  0,  0,
        1,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,
        0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  1